import getUID from '../utils/id';

import { observable } from 'mobx';

/**
 *
 */
class Property {
    @observable _name;
    @observable type;
    @observable defaultValue;
    @observable limitMin;
    @observable limitMax;
    @observable isRequired;
    @observable isAutoGenerated;
    @observable isSystem;
    @observable description;

    constructor(options = {}) {
        this.id = options.id || getUID();
        this._name = options.name || 'New_Property';
        this.type = (options.type || '');
        this.defaultValue = options.defaultValue || '';
        this.limitMin = options.limitMin || '';
        this.limitMax = options.limitMax || '';
        this.isRequired = options.isRequired || false;
        this.isAutoGenerated = options.isAutoGenerated || false;
        this.isSystem = options.isSystem || false;
        this.description = options.description || '';
    }

    set name(newName) {
        this._name = newName.replace(' ', '_');
    }

    get name() {
        return this._name;
    }

}

export default Property;