import getUID from '../utils/id';

import { observable } from 'mobx';
import {intercept} from "mobx/lib/mobx";

/**
 *
 */
class Property {
    @observable name;
    @observable type;
    @observable defaultValue;
    @observable limitMin;
    @observable limitMax;
    @observable isRequired;
    @observable isAutoGenerated;
    @observable isSystem;
    @observable description;

    constructor(options = {}) {
        this.id = options.id || getUID();
        this.name = options.name || 'New_Property';
        this.type = (options.type || '');
        this.defaultValue = options.defaultValue || '';
        this.limitMin = options.limitMin || '';
        this.limitMax = options.limitMax || '';
        this.isRequired = options.isRequired || false;
        this.isAutoGenerated = options.isAutoGenerated || false;
        this.isSystem = options.isSystem || false;
        this.description = options.description || '';

        intercept(this, 'name', change => {
            if (change.newValue === '') {
                return null;
            }

            change.newValue = change.newValue.replace(' ', '_');
            return change;
        });
    }
}

export default Property;