
import Property from "./Property";

const systemProperties = [
    new Property({
        name: 'id',
        type: 'id',
        isRequired: true,
        isAutoGenerated: true,
        isSystem: true
    }),
    new Property({
        name: 'creation_at',
        type: 'datetime',
        isRequired: true,
        isAutoGenerated: true,
        isSystem: true
    }),
    new Property({
        name: 'updated_at',
        type: 'datetime',
        isRequired: true,
        isAutoGenerated: true,
        isSystem: true
    })
];

export default systemProperties;