import React, {Component} from 'react';

import {TextField} from 'office-ui-fabric-react/lib/TextField';

import { Dropdown } from 'office-ui-fabric-react/lib/Dropdown';
import { Toggle } from 'office-ui-fabric-react/lib/Toggle';
import { observer } from "mobx-react";

const TYPES = ['', 'String', `ID`, 'Int', 'Float', 'Boolean', 'Password', 'Email', 'URL', 'Datetime', 'LatLng'];
const typesWithLimits = ['string', 'int', 'float', 'password', 'email', 'url'];

const hasLimits = (type) => typesWithLimits.includes(type.toLowerCase());

@observer
class Property extends Component {

    render() {
        const prop = this.props.data;

        console.log(prop);

        return (
            <div className="property">
                { JSON.stringify(prop) }
                <ul>
                    <li>
                        Name:
                        <TextField
                            value={prop.name}
                            onChanged={(val) => { prop.name = val; }}
                        />
                    </li>
                    <li>
                        Type:
                        <Dropdown
                            placeHolder='Select an Option'
                            label='Basic uncontrolled example:'
                            id='Basicdrop1'
                            ariaLabel='Basic dropdown example'
                            options={
                                TYPES.map(type => ({
                                    key: type.toLowerCase(),
                                    text: type
                                }))
                            }
                            onChanged={(option) => { prop.type = option.key; }}
                        />
                    </li>
                    <li>
                        Required:
                        <Toggle
                            defaultChecked={ false }
                            onText='Yes'
                            offText='No'
                            onChanged={(val) => { prop.isRequired = val; }}
                        />
                    </li>
                    <li>
                        Auto Gen.:
                        <Toggle
                            defaultChecked={ false }
                            onText='Yes'
                            offText='No'
                            onChanged={(val) => { prop.isAutoGenerated = val; }}
                        />
                    </li>
                    { hasLimits(prop.type) &&
                        <li>
                            Min Len.: <TextField onChanged={(val) => { prop.limitMin = val; }} />
                        </li>
                    }
                    { hasLimits(prop.type) &&
                        <li>
                            Max Len.: <TextField onChanged={(val) => { prop.limitMax = val; }} />
                        </li>

                    }
                    { !prop.isAutoGenerated &&
                    <li>
                        Default Value: <TextField onChanged={(val) => { prop.defaultValue = val; }} />
                    </li>
                    }
                    <li>
                        Description: <TextField onChanged={(val) => { prop.description = val; }} />
                    </li>
                </ul>
            </div>
        );
    }
}

export default Property;